tracker may be space separated list

diff --git a/bin/btfc b/bin/btfc
--- a/bin/btfc
+++ b/bin/btfc
@@ -31,7 +31,7 @@
 ######################################################################
 # Script version is YYmmdd-HHMM in UTC, date +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=141205-064217
+SCRIPTVERSION=141205-065018
 
 ######################################################################
 # Variables
@@ -357,12 +357,17 @@ kill_bt_client() {
 start_bt_client() {
   ########## TODO find unused port number
   ########## launch transmission-cli $1, prefix_meta/$1{.pid,.log}
-  umask 077
-  transmission-cli -M -er -v -w "${prefix_data}" "${prefix_meta}/${1}.torrent" \
-    >"${prefix_meta}/${1}.log" 2>&1 &
-  echo $! >"${prefix_meta}/${1}.pid"
-  umask 022
-  sleep 1
+  if [ -e "${prefix_meta}/${1}.torrent" ]; then
+    umask 077
+    transmission-cli -M -er -v -w "${prefix_data}" "${prefix_meta}/${1}.torrent" \
+      >"${prefix_meta}/${1}.log" 2>&1 &
+    echo $! >"${prefix_meta}/${1}.pid"
+    umask 022
+    sleep 1
+  else
+    echo "ERROR: Torrent meta file not found: ${prefix_meta}/${1}.torrent" >&2
+    exiterror 1
+  fi
 }
 
 stop_and_run_script() {
@@ -405,7 +410,9 @@ create_torrent_meta() {
   fi
   ########## Tracker is $tracker or dynamic
   if [ -n "${tracker}" ]; then
-    TRACKERURL="-t https://${tracker}/announce"
+    for i in ${tracker} ; do
+      TRACKERURL="$TRACKERURL -t https://${i}/announce"
+    done
   else
     for i in `ifconfig | sed 's/netmask.*//' | \
         egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}" | \
